networks:
  localhost_default:
    name: localhost_default
    external: true

services:
  app:
    command: bash -c "yarn && yarn dev"
    environment:
      YARN_CACHE_FOLDER: /cache
      HOST: "`${PROJECT_URL}`"
    expose:
      - 3000
    image: node:18
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=localhost_default"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${PROJECT_URL}`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"
    networks:
      - default
      - localhost_default
    tty: true
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ".:/app"
      - "$HOME/.cache/yarn:/cache"
    working_dir: /app
